credentials:
  usernames:
    Tu:
      email: tu@gmail.com
      name: Thi Minh Tu
      password: Protein # To be replaced with hashed password
    Tyler:
      email: nyan@gmail.com
      name: Nyan Htun
      password: Vitamin A # To be replaced with hashed password
cookie:
  expiry_days: 10
  key: abcdefqwe # Must be string
  name: choc_cookie
preauthorized:
  emails:
  - melsby@gmail.com